const ActionType = {
  SHOW_REGISTER: "SHOW_REGISTER",
  SHOW_LOGIN: "SHOW_LOGIN",
  HIDDEN_REGISTER: "HIDDEN_REGISTER",
  HIDDEN_LOGIN: "HIDDEN_LOGIN",
  CHECK_LOGIN: "CHECK_LOGIN",
  CHECK_LOGOUT: "CHECK_LOGOUT",
  SELECTED_KEY:'SELECTED_KEY'
};
export default ActionType;
